version: "2"
exclude_patterns:
  - backend/.github/
  - backend/build/
  - backend/dist/
  - backend/mock/
  - backend/node_modules/
  - backend/plop-templates/
  - backend/public/
  - backend/tests/
  - backend/src/vendor/