version: '3'
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    networks:
      - internal
    ports: 
      - 8080:9527
    volumes:
      - ./backend:/app
    command: /bin/bash -c "yarn && yarn run dev"

networks:
  internal:
    driver: bridge
