version: '3'
services:
  app:
    build:
      context: ./backend
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-webadmin:${VERSION}
    ports: 
      - 8081:80
    # volumes:
      # - ./backend/src:/app/src
      # - ./backend/tests:/app/tests
    env_file:
      - .env

    networks:
      dev-jds-network:
         ipv4_address: 10.166.0.2

networks:
  dev-jds-network:
      ipam:
          driver: default
          config:
             - subnet: 10.166.0.0/24
      

