version: '3'
services:
  app:
    build:
      context: ./backend
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-webadmin:${IMAGETAG}
    networks:
      - internal
    ports: 
      - 8081:8080
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/build
    env_file:
      - .env

networks:
  internal:
    driver: bridge
