version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-app/sapawarga-backend:${IMAGETAG}
    networks:
      - internal
    ports: 
      - 80:80

networks:
  internal:
    driver: bridge
