version: '3'
services:
  app:
    build:
      context: ./backend
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-webadmin:latest
    networks:
      - internal
    ports: 
      - 8081:80
    # volumes:
      # - ./backend/src:/app/src
      # - ./backend/tests:/app/tests
    env_file:
      - .env
      
networks:
  internal:
    driver: bridge
