version: '3'
services:
  app:
    build:
      context: ./backend
    networks:
      - internal
    ports: 
      - 8080:8080
    volumes:
      - ./backend:/app
      - .env.production:/app/.env.development
      - /app/node_modules
      - /app/build
    environment:
      - NODE_ENV=development

networks:
  internal:
    driver: bridge
