version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-app/sapawarga-backend:${IMAGETAG}
    networks:
      - internal
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist

networks:
  internal:
    driver: bridge
