version: '3'
services:
  app:
    build:
      context: ./backend
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-webadmin:${VERSION}
    networks:
      - internal
    ports: 
      - 8081:8080
    volumes:
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
    env_file:
      - .env-dev

networks:
  internal:
    driver: bridge
