version: '3'
services:
  app:
    build:
      context: ./backend
    networks:
      - internal
    ports: 
      - 8080:8080
    volumes:
      - ./backend:/app
    environment:
      - VUE_ENV_DEV=1
      - NODE_ENV=development

networks:
  internal:
    driver: bridge
