version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-webadmin/sapawarga-backend:${IMAGETAG}
    networks:
      - internal
    ports: 
      - 8080:80

networks:
  internal:
    driver: bridge
