version: '3'
services:
  backend:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-app/sapawarga-backend:latest
    networks:
      - internal
    # volumes:
      # - ./backend:/app
      # - /app/node_modules

networks:
  internal:
    driver: bridge
