kind: ConfigMap
apiVersion: v1
metadata:
  name: sapawarga-webadmin-config-env
  namespace: sapawarga
data:
  NODE_ENV: production
  VUE_APP_BASE_API: %VUE_APP_BASE_API%
  VUE_APP_VERSION: %VUE_APP_VERSION%
  SENTRY_DSN: %SENTRY_DSN%
  ERROR_ENVIRONMENT_DSN_PRODUCTION: %ERROR_ENVIRONMENT_DSN_PRODUCTION%
  ERROR_REPORT: %ERROR_REPORT%
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: sapawarga
data:
  .dockerconfigjson: %dockerconfigjson% # Base64 decoded={"auths": {"your.registry.host": {"auth": "username:password"}}}
type: kubernetes.io/dockerconfigjson