apiVersion: v1
kind: Service
metadata:
  name: sapawarga-webadmin
  namespace: sapawarga
spec:
  selector:
    app: sapawarga-webadmin
  ports:
  - name: webadmin-port
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort